---
- name: Upload to AWS S3 Bucket
  aws_s3:
    bucket: sunbird-04082022
    object: /artifacts/
    src: "{{ artifact_path }}" 
    mode: put
#   bucket: "{{ sunbird_artifact_storage_account_name }}"
#   object: "/{{ artifacts_container }}/{{ artifact }}"
#   src: "{{ artifact_path }}" 
#   mode: put
#   command: aws s3 cp {{ artifact_path }} s3://{{ artifacts_container }} 
#   async: 3600
#   poll: 10
